from flask import Flask, request, redirect, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['DEBUG'] = True
#connection string to connect to DB
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://1kb4k:1kb4k@localhost:8889/1kb4k'
#db type + database driver connecting db to app ://user:password@where database lives:port/name of database
app.config['SQLALCHEMY_ECHO'] = True #echoes the SQL commands generated by SQLAlchemy in the terminal

db = SQLAlchemy(app) 

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True) #primary key
    title = db.Column(db.String(120))
    author = db.Column(db.String(120))
    description = db.Column(db.String(600))

    def __init__(self, title, author, description):
        self.title = title
        self.author = author
        self.description = description

@app.route('/', methods=['POST', 'GET'])
def index():

    return render_template('index.html')


@app.route('/add-book', methods=['POST'])
def add_book():
    book_title = request.form['book_title']
    author_name = request.form['author_name'] 
    book_img_thumbnail = request.form['book_img_thumbnail']
    book_description = request.form['book_description']
    return render_template('addBook.html', book_title=book_title, author_name=author_name, book_description=book_description, book_img_thumbnail=book_img_thumbnail)

if __name__ == '__main__': 
    app.run()